# Single Project Page

title: DEPLI
email: lpsandaruwan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Depli is a handsome performance monitoring dashboard dedicated for looking into Java virtual machines through JMX remote connections.
  It is very user-friendly and does not ask you for tough configurations.
  Just run the Jar file and add a connection using web UI.


baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Social media links
facebook_username: skyblue1992
github_username:  lpsandaruwan
twitter_username: lpsandaruwan

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
