# Single Project Page

title: DEPLI
email: lpsandaruwan@gmail.com
description: >
  A handsome performance monitoring dashboard dedicated for looking into Java virtual machines through management
  bean server connections which provides the solution to monitor all the running Java applications at once with
  an attractive user interface.


baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Social media links
facebook_username: skyblue1992
github_username:  lpsandaruwan
twitter_username: lpsandaruwan

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
